title: let my heart be still/and this mystery explore
description: thoughts
author: anonymous unless u know me

theme: minima

markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# url + baseurl: fill these in once you know your github pages address.
# if your repo is "yourusername.github.io", leave baseurl blank.
# if your repo has any other name, set baseurl to "/that-repo-name".
url: "sheffly.github.io"
baseurl: ""

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor
